//
//  MedicationData.swift
//  formuWatch WatchKit Extension
//
//  Created by Daniel Ortiz on 10/9/21.
//

import SwiftUI

struct MedicationData: Identifiable {

    var id = UUID()
    var name: String
    var indications: String
    var contraindications: String
    var sideEffects: String
    var adultDosage: String
    var pediatricDosage: String
    var vialConcentration: String
}


let testData = [
    MedicationData(name: "Acetaminophen", indications: "Mild to moderate pain, Elevated temperature above 101.5", contraindications: "Known sensitivity", sideEffects: "Rare (hemolytic anemia and renal dysfunction)", adultDosage: "1,000mg", pediatricDosage: "15mg/kg", vialConcentration: "N/A"),
    MedicationData(name: "Adenosine", indications: "Stable Narrow Complex SVT, may be used for unstable narrow-complex reentry tachycardia while preparing for Cardioversion", contraindications: "Poison/Drug induced tachycardia, Second and Third degree blocks", sideEffects: "Facial flushing, chest pain or tightness, brief periods of asystole or bradycardia, ventricular ectopy", adultDosage: "6mg Rapid IV Push with 10cc NS Flush. 12mg Rapid IV Push with 10cc NS Flush", pediatricDosage: "0.1mg/kg max is 6mg IV Push with 5cc NS Flush. 0.2mg/kg max is 12mg IV Push with 5cc NS Flush", vialConcentration: "6mg/2mL"),
    MedicationData(name: "Albuterol", indications: "To relieve bronchospasm associated with asthma, bronchitis, anaphylaxis, or other reversible obstructive airway diseases", contraindications: "Known hypersensitivity symptomatic tachycardia", sideEffects: "Anxiety, restlessness, palpitations, hypertension, reflex tachycardia", adultDosage: "2.5mg in 3ml of NS via nebulizer over 5-15 minutes, may be repeated once 2.5mg in 3ml of NS via nebulizer over 5-15 minutes", pediatricDosage: "2.5mg in 3ml of NS via nebulizer over 5-15 minutes. May be repeated once 2.5mg in 3ml of NS via nebulizer over 5-15 minutes", vialConcentration: "N/A"),
    MedicationData(name: "Amiodarone", indications: "Pulseless VF/VT, Recurrent hemodynamically unstable V-tach (Runs of V-tach)(PVCs)", contraindications: "Hypersensitivity to Amiodarone, cardiogenic shock, sick sinus syndrome, history of torsades de pointes, severe bradycardia", sideEffects: "Bradycardia, dizziness, hypotension, prolonged QT interval", adultDosage: "Pulseless VF/VT 300mg IV/IO; 2nd dose 150mg IV/IO. Life threatening arrhythmias 150mg in 100 ml NS IV over 10minutes may repeat with max 2.2g over 24 hours", pediatricDosage: "Pulseless VF/VT 5mg/kg max 300mg; 2nd dose 5mg/kg max 300mg", vialConcentration: "150mg/3mL"),
    MedicationData(name: "Aspirin", indications: "New onset of chest pain suggestive of MI", contraindications: "Hypersensitivity to aspirin, GI bleed, intracranial bleed, children with fever, 3rd trimester pregnancy", sideEffects: "Nausea, vomiting, prolonged bleeding time", adultDosage: "324mg PO or chewed (4 baby aspirin)", pediatricDosage: "None", vialConcentration: "N/A"),
    MedicationData(name: "Atropine", indications: "Symptomatic Bradycardia, Organophosphate poisoning, Premedication for pediatric RSI if indicated", contraindications: "Myocardial ischemia (increases oxygen demand), Not effective in 2nd Degree type 2 AV block and 3rd Degree AV block", sideEffects: "Headache, confusion, dry mouth, nausea, vomiting, hypertension, abdominal pain", adultDosage: "Bradycardia: 1mg IV if needed every 3-5 minutes max 0.04mg/kg. Organophosphate Poisoning: 2-5mg", pediatricDosage: "Bradycardia: 0.02mg/kg max single dose 0.5mg may repeat only once for a max of 1.0mg Adolescence single dose not to exceed 0.5mg max dose of 3.0mg. Organophosphate: 0.02-0.05mg/kg may repeat in 20-30 minutes Adolescence 2mg initially, then if needed 1-2mg in 20-30 minutes. RSI: 0.01-0.02mg/kg (max dose 0.5mg)", vialConcentration: "1mg/10mL"),
    MedicationData(name: "Dextrose 50%", indications: "Hypoglycemia (documented or strongly suspected in absence of glucometer)", contraindications: "None in emergency setting", sideEffects: "Hyperglycemia", adultDosage: "12.5-25g IV", pediatricDosage: "Dilute to 25% (spill half then draw 25ml of NS). 0.5-1mg/kg or 2-4ml/kg. Dilute to 10% (spill 40ml then draw 40ml of NS)", vialConcentration: "25g/50mL"),
    MedicationData(name: "Diazepam", indications: "Generalized seizure, status epilepticus, sedation before cardioversion or pacing, extreme anxiety", contraindications: "Acute narrow angle glaucoma, Pregnancy", sideEffects: "Drowsiness, fatigue, dizziness, vertigo, hypotension, tachycardia, nausea, hiccups, coughing, laryngospasm", adultDosage: "Seizure 5-10mg; Anxiety 2-5mg. Sedation before cardioversion 5mg", pediatricDosage: "0.1-0.2mg/kg", vialConcentration: "N/A"),
    MedicationData(name: "Diltiazem", indications: "Symptomatic A-fib with rapid ventricular response", contraindications: "Severe hypotension systolic less than 90mmHg, heart block, heart failure", sideEffects: "Flushing, headache, bradycardia, hypotension, heart block, myocardial depression, at high doses cardiac arrest", adultDosage: "0.25mg/kg over 2 minutes max single dose 20mg if necessary after 15 minutes 0.35mg/kg over 2 minutes max dose 25mg", pediatricDosage: "Not recommended for pediatric patients", vialConcentration: "25mg/5mL"),
    MedicationData(name: "Diphenhydramine", indications: "Anaphylaxis, allergic reaction", contraindications: "Hypersensitivity to antihistamines, acute asthma", sideEffects: "Dizziness, drowsiness, anxiety, hypotension nausea, vomiting", adultDosage: "25-50mg", pediatricDosage: "1-2mg/kg", vialConcentration: "50mg/mL"),
    MedicationData(name: "Dopamine", indications: "Hemodynamic significant hypotension (70-90 mmHg systolic), Bradycardia non-responsive to atropine or pacing", contraindications: "Hypovolemia without corrected fluid loss VF and tachyarrhythmias", sideEffects: "Palpitations, tachyarrhythmias, nausea, vomiting", adultDosage: "5-20mcg/kg/min titrate to desired response. If CHF suspected max at 10mcg/kg/min", pediatricDosage: "2-20 mcg/kg/min titrate to desired response", vialConcentration: "N/A"),
    MedicationData(name: "Epinephrine", indications: "Anaphylaxis, cardiac arrest, Asthma, Croup", contraindications: "Cocaine induced VT, hypertension, cardiovascular disease", sideEffects: "Tachycardia, nausea, vomiting, anxiety, dizziness, weakness", adultDosage: "Anaphylaxis and Asthma: 0.3-0.5mg, for IV or IO use 1:10,000 concentration. 0.3-0.5mg For IM or subcutaneous use 1:1,000 concentration dose. Cardiac Arrest: 1mg for IV or IO 1:10,000 concentration ONLY every 3-5 minutes: NO IM dose for cardiac arrest", pediatricDosage: "Anaphylaxis and Asthma: 0.01mg/kg up to 0.15mg for IV or IO use 1:10,000 concentration. 0.01mg/kg up to 0.15mg for IM or subcutaneous use 1:1,000 concentration. Cardiac Arrest: 0.01mg/kg for IV or IO 1:10,000 concentration ONLY every 3-5 minutes: NO IM dose for cardiac arrest. Croup: 0.5ml/kg of up to 5ml diluted with 3ml NS 1:1,000 concentration only (requires online medical control)", vialConcentration: "1mg/10mL or 1mg/ml"),
    MedicationData(name: "Fentanyl", indications: "Short acting analgesic", contraindications: "MAO inhibitors within 14 days, asthma, myasthenia gravis", sideEffects: "Sedation, hypotension, circulatory depression, cardiac arrest, nausea and vomiting", adultDosage: "0.5mcg/kg to 1.5mcg/kg IV. May repeat every 2 minutes. (Single max dose of 100 mcg)", pediatricDosage: "0.5mcg/kg to 1.5mcg/kg IV. May repeat every 2 minutes. (Single max dose of 100 mcg)", vialConcentration: "100mcg/2mL"),
    MedicationData(name: "Furosemide", indications: "Treatment of edema associated with Congestive Heart Failure (CHF), Pulmonary Edema", contraindications: "Hepatic Coma, allergies to sulfonamides", sideEffects: "Headache, fatigue, orthostatic hypotension, hypokalemia, hypomagnesemia, metabolic acidosis", adultDosage: "40mg", pediatricDosage: "1mg/kg", vialConcentration: "40mg/4mL"),
    MedicationData(name: "Ipratropium Bromide", indications: "Asthma, bronchospasms associated with COPD, chronic bronchitis, and emphysema", contraindications: "Hypersensitivity to: atropine, bromides, peanut oils, soy lecithin. Closed angle glaucoma, children younger than 5 years of age", sideEffects: "Paradoxical acute bronchospasm, cough, headache, dizziness, palpitations, dry mouth", adultDosage: "0.5mg", pediatricDosage: "0.25-0.5mg", vialConcentration: "N/A"),
    MedicationData(name: "Ketamine", indications: "Induction procedures", contraindications: "Hypersensitivity, hypertension, elevated intracranial pressure, Caution in patients with severe hypertension (SBP > 160 mmHg) and conditions where worsening HTN is detrimental (e.g., cerebral hemorrhage, acute myocardial ischemia/infarction, thoracic/abdominal aneurysms)", sideEffects: "Increased intracranial pressure, increase intraocular pressure, nystagmus, respiratory depression when rapid IV administration in large doses", adultDosage: "Induction: 1mg/kg IV. Combative Patient: Adult 1-2mg/kg IV/IO or 4-5mg/kg IM. May repeat half the initial dose q 15 minutes as needed.", pediatricDosage: "Combative Patient: 1mg/kg IV/IO OR 3mg/kg IM", vialConcentration: "500mg/10ml"),
    MedicationData(name: "Labetalol", indications: "Severe Hypertension", contraindications: "Hypotension, bronchial asthma, severe bradycardia, heart block greater than 1st degree, NSAID or salicylate hypersensitivity", sideEffects: "Hypotension, nausea and vomiting, bradycardia, arrhythmia", adultDosage: "20mg slow push over 2 minutes", pediatricDosage: "Not indicated", vialConcentration: "20mg/4mL or 100mg/20mL"),
    MedicationData(name: "Lidocaine", indications: "RSI premedication to blunt increase in ICP", contraindications: "Wide complex escape beats associated with bradycardia", sideEffects: "Seizures without warning, cardiac arrhythmias, hypotension, cardiac arrest, Wolff-Parkinson White syndrome", adultDosage: "1-1.5mg/kg", pediatricDosage: "1mg/kg", vialConcentration: "100mg/5mL"),
    MedicationData(name: "Lorazepam", indications: "Status epilepticus, RSI preprocedure sedation, severe anxiety", contraindications: "Sensitivity to benzodiazepines, primary depressive disorders or psychosis, COPD, coma", sideEffects: "Headache, drowsiness, ataxia, dizziness, amnesia, depression, euphoria, fatigue, respiratory depression", adultDosage: "2mg over 1-2 minutes may repeat in 10-15 minutes. 2mg over 1-2 minutes", pediatricDosage: "0.05mg/kg over 1-2 minutes max dose 2mg may repeat in 10-15 minutes. 0.05mg/kg over 1-2 minutes max dose 2mg", vialConcentration: "2mg/mL"),
    MedicationData(name: "Magnesium Sulfate", indications: "Eclampsia (seizure), Torsades de pointes", contraindications: "AV block, myocardial damage, GI obstruction", sideEffects: "Flushing, sweating, depressed or absent reflexes, depressed cardiac function", adultDosage: "Pulseless Torsades de pointes: 1-2g in 10cc NS over 5-10 minutes. Pulse Torsades de pointes: 1-2g in 100cc NS over 5-60 minutes. Eclampsia: 2g over 20-30 minutes", pediatricDosage: "Pulse/Pulseless Torsades de pointes: 25-50mg/kg over 10-20 minutes", vialConcentration: "1g/2mL"),
    MedicationData(name: "Methylprednisolone Sodium Succinate", indications: "Management of acute bronchial asthma", contraindications: "Hypersensitivity, systemic fungal infection, Kaposi Sarcoma", sideEffects: "Depression, euphoria, headache, restlessness, hypertension, bradycardia, nausea and vomiting, swelling", adultDosage: "Acute Asthma: 125mg. Anaphylaxis: 1-2mg/kg/dose Max 125mg", pediatricDosage: "Asthma: 2mg/kg Max 125mg. Anaphylaxis: 1-2mg/kg Max 125mg", vialConcentration: "125mg/2mL"),
    MedicationData(name: "Midazolam", indications: "Sedation, Seizures, To impair memory of perioperative events", contraindications: "Intolerance to benzodiazepines, acute narrow-angle glaucoma, status asmaticus", sideEffects: "Retrograde amnesia, hypotension, nystagmus, respiratory arrest", adultDosage: "Induction: 0.1mg/kg IV. Seizures: 5 mg IV/IN or 10 mg IM; repeat as necessary every 2 - 5 minutes.", pediatricDosage: "Induction: 0.1mg/kg IV. Seizures: 0.05-0.2mg/kg IV/IM/IN; repeat as necessary every 2 - 5 minutes.", vialConcentration: "10mg/2mL"),
    MedicationData(name: "Morphine Sulfate", indications: "Moderate to sever pain associated with isolated fractures, burns, or amputations. Angina after use of nitroglycerin is exhausted. Congestive Heart Failure/Pulmonary Edema", contraindications: "Known sensitivity, respiratory depression, chemical induced pulmonary edema, Hypovolemia", sideEffects: "Hypotension, respiratory depression, euphoria, dizziness, worsening of bradycardia and heart block patients with acute inferior wall MI", adultDosage: "Analgesia: 2-5mg per dose up to 10mg slow push over 1-5 minutes. Chest pain associated with CHF/Pulmonary Edema: 2-4mg over 1-5 minutes low dosing recommended higher dosing can worsen hypoxia", pediatricDosage: "Analgesia: 6 months to 12 years: 0.05-0.1 mg/kg. Chest pain associated with CHF/Pulmonary Edema: 0.1mg/kg/dose IV or IO", vialConcentration: "N/A"),
    MedicationData(name: "Naloxone", indications: "Narcotic overdoses, drug of choice when depressant drug is not know", contraindications: "Hypersensitivity to Naloxone", sideEffects: "Nausea, vomiting, tachycardia, hypertension, narcotic withdrawal", adultDosage: "0.4-2mg higher doses may be necessary for synthetic narcotics", pediatricDosage: "Greater than 20kg: 2mg. Less than 20kg: 0.1mg/kg may repeat every 2-3 minutes", vialConcentration: "2mg/mL"),
    MedicationData(name: "Nitroglycerin", indications: "Angina, Hypertension, ongoing ischemic chest discomfort", contraindications: "Hypotension, ICP, intracranial bleeding, patients taking any medications for erectile dysfunction (Viagra, Cialis, Levitra)", sideEffects: "Headache, hypotension, bradycardia, lightheadedness, flushing", adultDosage: "0.4mg every 5 minutes until relief, hypotensive, or max: 1.2mg (3 doses)", pediatricDosage: "None for sublingual. *Contact online medical control if you believe you need it", vialConcentration: "0.4mg/tablet"),
    MedicationData(name: "Ondasetron Hydrochloride", indications: "Prevention of chemotherapy and radiation induced nausea and vomiting Prevention of nausea and vomiting with administration morphine sulfate", contraindications: "Hypersensitivity, following abdominal surgery", sideEffects: "Fever, headache, constipation, diarrhea, chest pain, and bronchospasm; Anaphylaxis (Rare)", adultDosage: "8mg", pediatricDosage: "Weight less than 40kg: 0.05-0.1mg/kg. Weight greater than 40kg: 4mg", vialConcentration: "4mg/2mL"),
    MedicationData(name: "Oxygen", indications: "Hypoxia, ischemic chest pain, respiratory distress, suspected carbon monoxide poisoning, shock, traumatic injuries", contraindications: "None in emergency setting", sideEffects: "None in emergency setting", adultDosage: "10-15LPM via Nonrebreather mask", pediatricDosage: "10-15lpm via Nonrebreather mask", vialConcentration: "N/A"),
    MedicationData(name: "Rocuronium Bromide", indications: "To induce neuromuscular blockade for the facilitation of ET intubation", contraindications: "Known sensitivity to bromides", sideEffects: "Muscle Paralysis, apnea, dyspnea, respiratory depression, sinus tachycardia, uticaria", adultDosage: "1mg/kg", pediatricDosage: "Older that 3 months: 0.6-1mg/kg", vialConcentration: "N/A"),
    MedicationData(name: "Sodium Bicarbonate", indications: "Acidosis", contraindications: "Metabolic alkalosis", sideEffects: "Metabolic alkalosis, hypernatremia, peripheral edema", adultDosage: "1mEq/kg slow push may repeat in 10 minutes. 0.5mEq/kg slow push", pediatricDosage: "1mEq/kg slow push may repeat in 10 minutes. 0.5mEq/kg slow push", vialConcentration: "50mEq/50mL"),
    MedicationData(name: "Succinylcholine", indications: "Produce skeletal muscle relaxation to facilitate endotracheal intubation", contraindications: "Malignant hyperthermia or family history of malignant hyperthermia, Burns older than 24 hours, children under 2 years of age", sideEffects: "Muscle fasciculations, Bradycardia, cardiac arrhythmias, hypotension, hyperkalemia", adultDosage: "1-1.5mg/kg over 10-30 seconds max 150mg may repeat dose", pediatricDosage: "1.0-1.5mg/kg", vialConcentration: "N/A"),
    MedicationData(name: "Thiamine", indications: "Delirium tremens, alcoholism, in conjunction with Dextrose 50%", contraindications: "Known sensitivity", sideEffects: "Itching, pain at injection site", adultDosage: "100mg slow push", pediatricDosage: "Not indicated. *Contact online medical control if you believe you need it", vialConcentration: "200mg/2mL"),
    MedicationData(name: "Vecuronium Bromide", indications: "To induce neuromuscular blockade for the facilitation of ET intubation", contraindications: "Known sensitivity to bromides, Children less than 10 years of age", sideEffects: "Muscle paralysis, apnea, dyspnea, sinus tachycardia", adultDosage: "0.1mg/kg", pediatricDosage: "10 years and older 0.1mg/kg", vialConcentration: "N/A"),
    MedicationData(name: "Etomidate", indications: "Sedation for RSI, Preferred agent for patients with severe hypertension (SBP > 160 mmHg)", contraindications: "Patient <10 yo, pregnancy, do not use with ketamine, immunosupression, adrenal insufficiency, sepsis, transplant patient", sideEffects: "Apnea, bradycardia, low BP, arrhythmias, N/V", adultDosage: " 0.3 mg/kg IV (maximum dose 40 mg)", pediatricDosage: " 0.3 mg/kg IV (maximum dose 40 mg)", vialConcentration: "N/A"),
    MedicationData(name: "Succinylcholine", indications: "Paralysis to for intubation", contraindications: "Known or suspected hyperkalemia, Severe crush or traumatic injuries > 2 days old, Spinal cord injuries > 24 hours old, renal failure, Pseudocholinesterase deficiencies, Known history of malignant hyperthermia, Neuromuscular disorders (e.g. muscular dystrophy), Penetrating eye injuries", sideEffects: "Apnea, malignant hyperthermia, dysrhythmias, low HR, HTN, low BP, cardiac arrest, hyperkalemia, high intraocular pressure", adultDosage: "1.5 - 2 mg/kg IV", pediatricDosage: "1.5 - 2 mg/kg IV  ", vialConcentration: "N/A"),
    MedicationData(name: "Tranexamic Acid", indications: "-----", contraindications: "Caution in patients with sepsis and patients at risk for adrenal insufficiency.", sideEffects: "-----", adultDosage: " 0.3 mg/kg IV (maximum dose 40 mg)", pediatricDosage: " 0.3 mg/kg IV (maximum dose 40 mg)", vialConcentration: "N/A"),
]





